CREATE TABLE Matches (
Id INT IDENTITY PRIMARY KEY,
Team1 NVARCHAR(30),
Team2 NVARCHAR(30),
MatchDate datetime
);

CREATE TABLE GroceryList (
Id INT IDENTITY PRIMARY KEY,
Ingredients NVARCHAR(500),
MatchId INT FOREIGN KEY REFERENCES Matches(Id),
);